---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cert-manager
  description: Cert manager
  annotations:
    github.com/project-slug: schabo/helm-cert-manager
    argocd/app-name: cert-manager
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app=cert-manager'
  links:
    - url: https://github.com/schabo/helm-cert-manager
      title: Cert Manager repository
      icon: github
      type: Code
    - url: https://cert-manager.io/
      title: Cert Manager website
      icon: docs
      type: docs
  tags:
    - certificate
    - cert-manager

spec:
  type: code
  owner: schabo
  lifecycle: production

