cert-manager:
  global:
    commonLabels:
      backstage.io/kubernetes-id: cert-manager
      env: production
  crds:
    enabled: true
    keep: true
  config:
    apiVersion: controller.config.cert-manager.io/v1alpha1
    kind: ControllerConfiguration
    enableGatewayAPI: true